language: java
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c groovy-spock.conf --only=tests --test-run-id=106614

script:
  - mvn clean test

after_script:
  - hiptest-publisher -c groovy-spock.conf -p "target/surefire-reports/TEST-*.xml" --test-run-id=106614
